<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9mWAtUL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9mWAtUL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9mWAtUL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9mWAtUL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9mWAtUL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9mWAtUL',
    'container.build_id' => '6baae421',
    'container.build_time' => 1639368735,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9mWAtUL');
