<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9C0Zla5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9C0Zla5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9C0Zla5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9C0Zla5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9C0Zla5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9C0Zla5',
    'container.build_id' => 'b89cd216',
    'container.build_time' => 1638127948,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9C0Zla5');
